apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-pods
  namespace: default
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: cleanup-pods-sa
          containers:
          - command:
            - /bin/bash
            - -c
            - |
              now=$(date +%s)
              kubectl get pods -A -o json | jq -r --argjson now "$now" '
                .items[]
                | select(
                    .status.phase == "Failed" or
                    .status.reason == "Evicted" or
                    (
                      .status.phase == "Succeeded" and
                      (($now - ((.metadata.creationTimestamp | fromdateiso8601) | tonumber)) > 300)
                    )
                  )
                | "\(.metadata.namespace) \(.metadata.name)"
              ' | while read -r namespace name; do
                  kubectl -n "$namespace" delete pod "$name"
                done
              sleep 60s 
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            name: kubectl
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 30 7 * * *
  successfulJobsHistoryLimit: 0
  suspend: false