apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaniko-cache
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
